{"name": "test_failGetElement", "status": "failed", "statusDetails": {"message": "AssertionError", "trace": "self = <test_KWA_demo.test_KWA_Demo testMethod=test_failGetElement>\n\n    @qase.title('testFailGetElement')\n    def test_failGetElement(self):\n>       self.commands.testFailGetElement()\n\ntest_KWA_demo.py:32: \n_ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _\n\nself = <KWA_demo_commands.DemoCommands object at 0x000002B36C3C6E90>\n\n    def testFailGetElement(self):\n>       assert self.getElement(self._AutoSuggest) != None\nE       AssertionError\n\nKWA_demo_commands.py:86: AssertionError"}, "attachments": [{"source": "a3703d13-ca1a-41d4-8d08-b34fb7383d73-attachment.png", "type": "image/png"}, {"name": "log", "source": "388edf67-9eae-4022-8fbe-8ec292861e1e-attachment.txt", "type": "text/plain"}], "start": 1667219762677, "stop": 1667219789038, "uuid": "929c1d53-1047-451e-8bac-f8bea9e444ac", "historyId": "8da06a45c3678cd1e762e9eceade2cb0", "testCaseId": "6389d253f16a39b2d0e5481eaa902445", "fullName": "test_KWA_demo.test_KWA_Demo#test_failGetElement", "labels": [{"name": "tag", "value": "qase_title(title='testFailGetElement')"}, {"name": "tag", "value": "@pytest.mark.usefixtures('createClassDriver')"}, {"name": "suite", "value": "test_KWA_demo"}, {"name": "subSuite", "value": "test_KWA_Demo"}, {"name": "host", "value": "acer-laptop"}, {"name": "thread", "value": "17188-MainThread"}, {"name": "framework", "value": "pytest"}, {"name": "language", "value": "cpython3"}, {"name": "package", "value": "test_KWA_demo"}]}