{"name": "test_failGetElement", "status": "failed", "statusDetails": {"message": "AssertionError", "trace": "self = <test_KWA_demo.test_KWA_Demo testMethod=test_failGetElement>\n\n    @qase.title('testFailGetElement')\n    def test_failGetElement(self):\n>       self.commands.testFailGetElement()\n\ntest_KWA_demo.py:32: \n_ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _\n\nself = <KWA_demo_commands.DemoCommands object at 0x000001F3F00CEB60>\n\n    def testFailGetElement(self):\n>       assert self.getElement(self._AutoSuggest) != None\nE       AssertionError\n\nKWA_demo_commands.py:78: AssertionError"}, "attachments": [{"source": "c2e3077f-7b3e-4779-8b79-ffacadac918e-attachment.png", "type": "image/png"}, {"name": "log", "source": "3fecbe63-ad7c-4100-8c17-61a05cc77a89-attachment.txt", "type": "text/plain"}], "start": 1667218492445, "stop": 1667218518768, "uuid": "2afd7baf-6c40-4c9a-85f9-f3d947d04165", "historyId": "8da06a45c3678cd1e762e9eceade2cb0", "testCaseId": "6389d253f16a39b2d0e5481eaa902445", "fullName": "test_KWA_demo.test_KWA_Demo#test_failGetElement", "labels": [{"name": "tag", "value": "qase_title(title='testFailGetElement')"}, {"name": "tag", "value": "@pytest.mark.usefixtures('createClassDriver')"}, {"name": "suite", "value": "test_KWA_demo"}, {"name": "subSuite", "value": "test_KWA_Demo"}, {"name": "host", "value": "acer-laptop"}, {"name": "thread", "value": "3028-MainThread"}, {"name": "framework", "value": "pytest"}, {"name": "language", "value": "cpython3"}, {"name": "package", "value": "test_KWA_demo"}]}